"""Port: Calibration data storage."""
from __future__ import annotations
from datetime import datetime
from typing import List, Optional, Protocol, runtime_checkable
from twin_runtime.domain.models.calibration import (
    CalibrationCase, CandidateCalibrationCase, TwinEvaluation,
    OutcomeRecord, DetectedBias, TwinFidelityScore,
)
from twin_runtime.domain.models.primitives import DetectedBiasStatus
from twin_runtime.domain.models.runtime import RuntimeEvent


@runtime_checkable
class CalibrationStore(Protocol):
    """Store calibration lifecycle objects."""
    def save_candidate(self, candidate: CandidateCalibrationCase) -> str: ...
    def save_case(self, case: CalibrationCase) -> str: ...
    def save_evaluation(self, evaluation: TwinEvaluation) -> str: ...
    def save_event(self, event: RuntimeEvent) -> str: ...
    def list_cases(self, used: Optional[bool] = None) -> List[CalibrationCase]: ...
    def list_events(self, since: Optional[datetime] = None) -> List[RuntimeEvent]: ...
    def save_outcome(self, outcome: OutcomeRecord) -> str: ...
    def list_outcomes(self, trace_id: Optional[str] = None) -> List[OutcomeRecord]: ...
    def save_detected_bias(self, bias: DetectedBias) -> str: ...
    def list_detected_biases(self, status: Optional[DetectedBiasStatus] = None) -> List[DetectedBias]: ...
    def save_fidelity_score(self, score: TwinFidelityScore) -> str: ...
    def list_fidelity_scores(self, limit: int = 10) -> List[TwinFidelityScore]: ...
    def list_evaluations(self) -> List[TwinEvaluation]: ...
