"""Port: TwinState storage and retrieval."""
from __future__ import annotations
from typing import List, Optional, Protocol, runtime_checkable
from twin_runtime.domain.models.twin_state import TwinState


@runtime_checkable
class TwinStateStore(Protocol):
    """Store and retrieve versioned TwinState snapshots."""
    def save_state(self, state: TwinState) -> str: ...
    def load_state(self, user_id: str, version: Optional[str] = None) -> TwinState: ...
    def list_versions(self, user_id: str) -> List[str]: ...
    def has_current(self, user_id: str) -> bool: ...
    def rollback(self, user_id: str, version: str) -> TwinState: ...
