"""HTML comparison report generator."""

from __future__ import annotations

import html
from datetime import datetime, timezone
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from twin_runtime.application.comparison.schemas import ComparisonReport

_CSS = """
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f5f5; color: #333; }
.container { max-width: 1000px; margin: 0 auto; padding: 24px; }
h1 { font-size: 1.8em; margin-bottom: 4px; }
h2 { font-size: 1.2em; margin: 24px 0 12px; color: #555; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
.meta { color: #888; font-size: 0.9em; margin-bottom: 20px; }

/* Summary Cards */
.cards { display: flex; gap: 16px; flex-wrap: wrap; }
.card { background: #fff; border-radius: 8px; padding: 16px 20px; flex: 1; min-width: 180px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
.card.best { border-left: 4px solid #2ecc71; }
.card h3 { font-size: 0.85em; color: #888; text-transform: uppercase; letter-spacing: 0.5px; }
.card .value { font-size: 1.8em; font-weight: 700; margin-top: 4px; }
.card .detail { font-size: 0.8em; color: #999; }

/* Bar Chart */
.bar-chart { margin: 12px 0; }
.bar-row { display: flex; align-items: center; margin: 6px 0; }
.bar-label { width: 120px; font-size: 0.9em; text-align: right; padding-right: 12px; }
.bar-track { flex: 1; background: #eee; border-radius: 4px; height: 28px; position: relative; }
.bar-fill { height: 100%; border-radius: 4px; display: flex; align-items: center; padding-left: 8px; font-size: 0.8em; color: #fff; font-weight: 600; }
.bar-fill.vanilla { background: #95a5a6; }
.bar-fill.persona { background: #3498db; }
.bar-fill.rag_persona { background: #9b59b6; }
.bar-fill.twin { background: #2ecc71; }
.baseline-line { position: absolute; left: 85%; top: -4px; bottom: -4px; border-left: 2px dashed #e74c3c; z-index: 1; }
.baseline-label { position: absolute; left: 85%; top: -18px; font-size: 0.7em; color: #e74c3c; transform: translateX(-50%); white-space: nowrap; }

/* Scenario Table */
table { width: 100%; border-collapse: collapse; background: #fff; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
th { background: #f8f8f8; font-size: 0.8em; text-transform: uppercase; letter-spacing: 0.5px; color: #666; padding: 10px 12px; text-align: left; }
td { padding: 8px 12px; border-top: 1px solid #f0f0f0; font-size: 0.85em; }
tr:hover { background: #fafafa; }
.correct { color: #2ecc71; font-weight: 600; }
.incorrect { color: #e74c3c; }

/* Domain Breakdown */
.domain-group { margin: 8px 0; }
.domain-name { font-weight: 600; font-size: 0.9em; margin-bottom: 4px; }
.domain-bars { margin-left: 12px; }
.mini-bar { display: flex; align-items: center; margin: 3px 0; }
.mini-label { width: 100px; font-size: 0.8em; }
.mini-track { flex: 1; background: #eee; border-radius: 3px; height: 18px; max-width: 400px; }
.mini-fill { height: 100%; border-radius: 3px; font-size: 0.7em; color: #fff; display: flex; align-items: center; padding-left: 6px; }

footer { margin-top: 32px; text-align: center; color: #bbb; font-size: 0.8em; }
"""


def generate_comparison_report(report: "ComparisonReport") -> str:
    """Generate a single-file HTML comparison report."""
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    body = (
        _section_summary_cards(report)
        + _section_bar_chart(report)
        + _section_scenario_table(report)
        + _section_domain_breakdown(report)
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>A/B Comparison Report</title>
  <style>{_CSS}</style>
</head>
<body>
  <div class="container">
    <h1>A/B Baseline Comparison</h1>
    <p class="meta">Scenarios: {html.escape(report.scenario_set_name)} &middot; Generated: {generated_at}</p>
    {body}
    <footer>
      Generated by twin-runtime compare &middot; Human test-retest &asymp; 0.85 (Stanford digital twin research)
    </footer>
  </div>
</body>
</html>"""


def _section_summary_cards(report: "ComparisonReport") -> str:
    if not report.aggregates:
        return ""
    best_cf = max(a.cf_score for a in report.aggregates.values())
    cards = []
    for rid, agg in sorted(report.aggregates.items()):
        cls = "card best" if agg.cf_score == best_cf else "card"
        cards.append(f"""<div class="{cls}">
  <h3>{html.escape(rid)}</h3>
  <div class="value">{agg.cf_score:.0%}</div>
  <div class="detail">{agg.correct}/{agg.total} correct &middot; {agg.mean_latency_ms:.0f}ms avg</div>
</div>""")
    return f'<h2>Summary</h2>\n<div class="cards">{"".join(cards)}</div>'


def _section_bar_chart(report: "ComparisonReport") -> str:
    if not report.aggregates:
        return ""
    rows = []
    for rid, agg in sorted(report.aggregates.items()):
        pct = agg.cf_score * 100
        rows.append(f"""<div class="bar-row">
  <div class="bar-label">{html.escape(rid)}</div>
  <div class="bar-track">
    <div class="bar-fill {html.escape(rid)}" style="width:{pct:.1f}%">{agg.cf_score:.0%}</div>
    <div class="baseline-line"></div>
    <div class="baseline-label">Human ~0.85</div>
  </div>
</div>""")
    return f'<h2>CF Score Comparison</h2>\n<div class="bar-chart">{"".join(rows)}</div>'


def _section_scenario_table(report: "ComparisonReport") -> str:
    if not report.runner_outputs:
        return ""

    runner_ids = sorted(report.runner_outputs.keys())

    # Collect all scenario IDs from first runner
    first_runner_outputs = report.runner_outputs[runner_ids[0]]
    scenario_ids = [o.scenario_id for o in first_runner_outputs]

    # Build lookup: (runner_id, scenario_id) -> RunnerOutput
    lookup = {}
    for rid, outputs in report.runner_outputs.items():
        for o in outputs:
            lookup[(rid, o.scenario_id)] = o

    header = "<th>Scenario</th>" + "".join(f"<th>{html.escape(r)}</th>" for r in runner_ids)
    rows = []
    for sid in scenario_ids:
        cells = f"<td>{html.escape(sid)}</td>"
        for rid in runner_ids:
            o = lookup.get((rid, sid))
            if o:
                mark = "correct" if o.is_correct else "incorrect"
                symbol = "\u2713" if o.is_correct else "\u2717"
                cells += f'<td class="{mark}">{symbol} {html.escape(o.chosen)}</td>'
            else:
                cells += "<td>-</td>"
        rows.append(f"<tr>{cells}</tr>")

    return f"""<h2>Per-Scenario Results</h2>
<table>
<thead><tr>{header}</tr></thead>
<tbody>{"".join(rows)}</tbody>
</table>"""


def _section_domain_breakdown(report: "ComparisonReport") -> str:
    if not report.aggregates:
        return ""

    # Collect all domains across all runners
    all_domains = set()
    for agg in report.aggregates.values():
        for d in agg.domain_breakdown:
            all_domains.add(d.domain)

    if not all_domains:
        return ""

    groups = []
    for domain in sorted(all_domains):
        bars = []
        for rid, agg in sorted(report.aggregates.items()):
            bd = next((d for d in agg.domain_breakdown if d.domain == domain), None)
            if bd:
                pct = bd.cf_score * 100
                bars.append(f"""<div class="mini-bar">
  <div class="mini-label">{html.escape(rid)}</div>
  <div class="mini-track"><div class="mini-fill {html.escape(rid)}" style="width:{pct:.1f}%">{bd.cf_score:.0%}</div></div>
</div>""")
        groups.append(f"""<div class="domain-group">
  <div class="domain-name">{html.escape(domain)}</div>
  <div class="domain-bars">{"".join(bars)}</div>
</div>""")

    return f'<h2>Domain Breakdown</h2>\n{"".join(groups)}'
